name: Pull Request Test (non-x64)

on: 
  pull_request:
    branches: 
      - main

jobs:
  build_macos_aarch64:
    name: Build for macOS aarch64
    if: "!contains(github.event.head_commit.message, '[skip macos-aarch64]')"
    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      matrix:
        arch: [DEIGEN_DONT_VECTORIZE, DDUMMY]
        eigenversion: [3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.4.0]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: |
        wget https://gitlab.com/libeigen/eigen/-/archive/${{ matrix.eigenversion }}/eigen-${{ matrix.eigenversion }}.tar.gz
        tar -zxvf eigen-${{ matrix.eigenversion }}.tar.gz
        mv eigen-${{ matrix.eigenversion }} include
    - name: Build
      run: |
        export EIGEN_PATH=`pwd`/include
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DEIGENRAND_CXX_FLAGS="-${{ matrix.arch }} -I${EIGEN_PATH}" ../
        make
    #- name: Test
    #  run: |
    #    ./build/test/EigenRand-test
    #- name: Run Accuracy
    #  run: |
    #    ./build/EigenRand-accuracy

  build-arm64:
    name: Build for Arm64-Centos7
    if: "!contains(github.event.head_commit.message, '[skip arm64]')"
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        arch: [DEIGEN_DONT_VECTORIZE, march=native]
        eigenversion: [3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.4.0]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: bab2min/run-on-arch-action@use-custom-image
      id: runcmd
      with:
        image: quay.io/pypa/manylinux2014_aarch64
        githubToken: ${{ github.token }}
        setup: |
          mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
        run: |
          git clone https://gitlab.com/libeigen/eigen
          pushd eigen
          git checkout tags/${{ matrix.eigenversion }}
          popd
          mv eigen include
          export EIGEN_PATH=`pwd`/include
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DEIGENRAND_CXX_FLAGS="-${{ matrix.arch }} -I${EIGEN_PATH}" ../
          make
          ctest -R test
          ctest -R accuracy
